steps:
- name: 'ubuntu'
  args: ['apt-get', 'install', 'build-essential']
- name: 'ubuntu'
  args: ['apt', 'install', 'curl']
- name: 'ubuntu'
  args: ['curl', '-sl', 'https://deb.nodesource.com/setup_6.x', '|', 'sudo', 'bash', '-']
- name: 'ubuntu'
  args: ['sudo', 'apt-get', 'install', '-y', 'nodejs']
- name: 'ubuntu'
  args: ['npx', 'install']
- name: 'ubuntu'
  args: ['npx', 'playwright', 'install', '--with-deps']
- name: 'ubuntu'
  args: ['npx', 'playwright', 'install-deps']
- name: 'ubuntu'
  args: ['npx', 'playwright', 'test',  '--timeout=60000',  '--retries=3']