steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npx
  args: ['playwright', 'install', '--with-deps']
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npx
  args: ['playwright', 'install-deps']
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npx
  args: ['playwright', 'test',  '--timeout=60000',  '--retries=3']