steps:
- name: 'debian'
  args: ['apt', 'install', 'nodejs']
- name: 'debian'
  args: ['npx', 'install']
- name: 'debian'
  args: ['npx', 'playwright', 'install', '--with-deps']
- name: 'debian'
  args: ['npx', 'playwright', 'install-deps']
- name: 'debian'
  args: ['npx', 'playwright', 'test',  '--timeout=60000',  '--retries=3']